// Generated by CoffeeScript 1.3.3
(function() {
  var Email, app, express, settings;

  Email = require('email').Email;

  express = require('express');

  settings = (require('./settings')).init();

  app = express();

  app.configure(function() {
    app.use(express.logger());
    app.use(express.favicon());
    app.use(express.bodyParser());
    return app.use(function(q, s, n) {
      s.setHeader('Access-Control-Allow-Origin', 'http://cracktheplates.com');
      s.setHeader('Access-Control-Allow-Credentials', 'true');
      return n();
    });
  });

  app.post('/suggest', function(req, res) {
    var k, v, _ref;
    if ((_ref = req.body.human.toLowerCase()) !== '12' && _ref !== 'twelve') {
      console.error('not a human');
      return res.send(500);
    } else {
      return (new Email({
        from: 'atlvegguide@atlvegguide.com',
        to: settings.to_email,
        subject: "vegguide suggestion: " + req.body.name,
        body: ((function() {
          var _ref1, _results;
          _ref1 = req.body;
          _results = [];
          for (k in _ref1) {
            v = _ref1[k];
            _results.push("" + k + ": " + v);
          }
          return _results;
        })()).join("\n")
      })).send(function(err) {
        if (err) {
          console.error(err);
        }
        return res.send(err ? 500 : 200);
      });
    }
  });

  app.listen(settings.port);

  console.log("listening on port " + settings.port);

}).call(this);
